name: ExperienceShelves
version: 1.0.1
main: com.majora.minecraft.experienceshelves.ExperienceShelves

description: A simple plugin which allows a player to store and withdraw experience in bookshelves. Inspired by the defunct mode MagicBookshelf by Derthmonuter.
author: majora2007
dev-url: http://dev.bukkit.org/bukkit-plugins/exp-shelves/
database: false

commands:
  experienceshelves:
    aliases: [xps]
    description: Lock the vault directly infront of player or view balance of.
    usage: |
      /<command> lock - Lock the vault directly infront of player.
      /<command> balance - Display the balance of vault directly infront of player.
      /<command> move start - Start the move of a vault. Note if you don't end and log off, you will loose all xp in vault.
      /<command> move end - End the move of a vault.
    
permissions:
  experienceshelves.*:
    description: Gives access to all <plugin name> commands
    children:
      experienceshelves.lock: true
      experienceshelves.balance: true
      experienceshelves.break: true
      experienceshelves.store: true
      experienceshelves.withdraw: true
      experienceshelves.snoop: true
      experienceshelves.create: true
      experienceshelves.move: true
  experienceshelves.lock:
    description: Allows you to lock an xp container
    default: op
  experienceshelves.balance:
    description: Allows you to view balance of an xp container
    default: true
  experienceshelves.move:
    description: Allows you to move an xp container without loosing xp inside.
    default: true
  experienceshelves.break:
    description: Allows your to break an xp container that is not owned by you
    default: op
  experienceshelves.store:
    description: Allows you to store xp in an xp container
    default: true
  experienceshelves.withdraw:
    description: Allows you to withdraw xp from an xp container
    default: true
  experienceshelves.snoop:
    description: Allows you to run commands on an xp container you do not own
    default: op
    children:
      experienceshelves.balance: true
      experienceshelves.lock: true
  experienceshelves.create:
    description: Allows you to create an xp container
    default: false